import type { Metadata } from 'next'
import { PrimeReactProvider } from 'primereact/api'
import Providers from '../../providers'
import 'primereact/resources/themes/lara-light-indigo/theme.css'
import '../../globals.css'
import '/public/assets/fonts/stylesheet.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {


    return (
        <html lang="en">
            <PrimeReactProvider>
                <body className='overflow-hidden'>
                    {/* <Header /> */}
                    <Providers>{children}</Providers>
                    {/* <Footer /> */}
                </body>
            </PrimeReactProvider>
        </html>
    )
}
